###############################################################################
# Developer's configuration file for the ESMValTool
###############################################################################
# This file retains the project- and machine-dependent directory and file name
# definitions of the input and output data
# Each dictionary is structured as follows
#
# PROJECT:
#   input_dir:
#     default:
#     drs1:
#     drs2:
#     etc:
#   input_file:
#   output_file:
#
# Only the default drs is mandatory, the others are optional
###############################################################################
---
ECEARTH:
  input_dir:
    default: '/'
    # BSC: '{expid}/cmorfiles/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
    BSC: '{exp}/ecearth/HighResMIP/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{version}'
  input_file: '{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}_*.nc'
  # input_fx_dir:
  #   default: '/'
  #   BSC: '{expid}/cmorfiles/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{fx_var}/{grid}/{latestversion}'
  # input_fx_file: '{fx_var}_fx_{dataset}_{exp}_r0i0p0.nc'
  output_file: '{project}_{dataset}_{mip}_{exp}_{ensemble}_{short_name}'
  # cmor_type: 'CMIP6'
  institutes:
    'EC-Earth3P': ['EC-Earth-Consortium']
    'EC-Earth3-HR': ['EC-Earth-Consortium']
    'EC-Earth3P-HR': ['EC-Earth-Consortium']

PRIMAVERA:
  input_dir:
    default: '/'
    BSC: '{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
  input_file: '{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}_*.nc'
  output_file: '{project}_{dataset}_{mip}_{exp}_{ensemble}_{short_name}'
  cmor_type: 'CMIP6'
  institutes:
    'EC-Earth3P': ['EC-Earth-Consortium']
    'EC-Earth3P-HR': ['EC-Earth-Consortium']

LENS:
  input_dir:
    default: '/'
    BSC: 'jcos/ncar/{dataset}/{ensemble}/{short_name}'
  input_file: '{dataset}_{short_name}_{ensemble}_*.nc'
  output_file: '{dataset}_{short_name}_{ensemble}'

DPLE:
  input_dir:
    default: '/'
    BSC: 'jcos/ncar/{dataset}/{ensemble}/{short_name}'
  input_file: '{dataset}_{short_name}_{ensemble}_{startdate}_*.nc'
  output_file: '{dataset}_{short_name}_{ensemble}'
  # cmor_type: 'CMIP6'

NCAR:
  input_dir:
    default: '/'
  #   BSC: 'jcos/ncar/{dataset}/{ensemble}/{short_name}'
  # input_file: '{dataset}_{short_name}_{ensemble}_{startdate}_*.nc'
  # output_file: '{dataset}_{short_name}_{ensemble}'
    BSC: '/exp/ncar/{dataset}/monthly_mean/{short_name}-latlon'
  input_file: '{short_name}_*.nc'
  output_file: '{dataset}_{short_name}'
  # cmor_type: 'CMIP6'

CORDEX_test:
  input_dir:
    default: '/'
    BSC: 'jcos'
  # input_file: '{short_name}_EUR-11_{institute}-{dataset}_{exp}_{ensemble}_*-{rcm}_{version}_{freq}_*.nc'
  # input_file: '{short_name}*EUR-11_*-{dataset}_{exp}_{ensemble}_*-{rcm}_{version}_{mip}_*.nc'
  input_file: '{short_name}_{domain}_{driver}_{exp}_{ensemble}_{institute}-{dataset}_{rcm_version}_{mip}*.nc'
  output_file: '{short_name}_{dataset}_{exp}_{ensemble}_{rcm_version}_{mip}'
  # output_file: '{project}_{dataset}-{rcm}_{mip}_{exp}_{ensemble}_{short_name}'
  cmor_strict: false
  cmor_type: CMIP5

CORDEX:
  input_dir:
    default: '/'
    BSC: '{exp}/{dataset.lower}-{rcm.lower}'
  # input_file: '{short_name}_EUR-11_{institute}-{dataset}_{exp}_{ensemble}_*-{rcm}_{version}_{freq}_*.nc'
  input_file: '{short_name}*EUR-11_{institute}-{dataset}_{exp}_{ensemble}_*-{rcm}_{version}_*.nc'
  output_file: '{project}_{dataset}-{rcm}_{mip}_{exp}_{ensemble}_{short_name}'
  cmor_strict: false
  cmor_type: CMIP5
  
HIGHRESMIP:
  input_dir:
    default: '/'
    BSC: '{exp}/{dataset.lower}/HighResMIP_{expid}/HighResMIP/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
  input_file: '{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}_*.nc'
  output_file: '{project}_{dataset}_{mip}_{exp}_{ensemble}_{short_name}'
  cmor_type: 'CMIP6'
  institutes:
     'CMCC-CM2-HR4': ['CMCC']
     'CMCC-CM2-VHR4': ['CMCC']
     'HadGEM3-GC31-HH': ['MOHC']
     'HadGEM3-GC31-HM': ['MOHC']
     'HadGEM3-GC31-LL': ['MOHC']
     'HadGEM3-GC31-MM': ['MOHC']
     'ECMWF-IFS-HR': ['ECMWF']
     'ECMWF-IFS-LR': ['ECMWF']
     'ECMWF-IFS-MR': ['ECMWF']
     'GFDL-CM4C192': ['NOAA-GFDL']
     'INM-CM5-H': ['INM']
     'MPI-ESM1-2-HR': ['MPI-M']
     'MPI-ESM1-2-XR': ['MPI-M']
     'EC-Earth3P': [EC-Earth-Consortium]
     'EC-Earth3P-HR': [EC-Earth-Consortium]

CMIP6:
  input_dir:
    default: '/'
    BADC: '{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
    DKRZ: '{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
    ETHZ: '{exp}/{mip}/{short_name}/{dataset}/{ensemble}/{grid}/'
    BSC: 
      - '{exp}/{dataset}/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}' 
      - '{exp}/{dataset}/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}' 
    CIMA:
      - '{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
    JASMIN:
      - '{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
  input_file: '{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}*.nc'
  output_file: '{project}_{dataset}_{mip}_{exp}_{ensemble}_{short_name}'
  cmor_type: 'CMIP6'

PEP:
  input_dir:
    default: '/'
    BADC: '{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
    DKRZ: '{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
    ETHZ: '{exp}/{mip}/{short_name}/{dataset}/{ensemble}/{grid}/'
    BSC: 
      - '{short_name}/ncar-dple/pep' 
  input_file: '{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}*'
  output_file: '{project}_{dataset}_{mip}_{exp}_{ensemble}_{short_name}'
  cmor_type: 'CMIP6'

autoCMIP6:
  input_dir:
    default: '/'
    BADC: '{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
    DKRZ: '{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
    ETHZ: '{exp}/{mip}/{short_name}/{dataset}/{ensemble}/{grid}/'
    BSC: 
      - '{exp}/{dataset}/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}' 
      - '{exp}/{dataset}/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}' 
  input_file: '{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}*'
  output_file: '{project}_{dataset}_{mip}_{exp}_{ensemble}_{grid}_{short_name}'
  cmor_type: 'CMIP6'


grCMIP5:
  cmor_strict: true
  input_dir:
    default: '/'
    BSC: 
      - '{exp}/{dataset.lower}/cmip5-{expid}/{experiment_family}/*/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
      - '{exp}/{dataset.lower}/cmip5-{expid}/{experiment_family}/*/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/*'
      - '{exp}/{dataset.lower}/cmip5-{expid}/{experiment_family}/*/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}'
  input_file: '{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}_*'
  output_file: '{project}_{dataset}_{mip}_{exp}_{ensemble}_{grid}_{short_name}'
  cmor_type: "CMIP6"

CMIP5:
  cmor_strict: true
  input_dir:
    default: '/'
    BADC: '{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/latest/{short_name}'
    CP4CDS: '{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/{short_name}/latest/'
    DKRZ: '{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/{latestversion}/{short_name}'
    ETHZ: '{exp}/{mip}/{short_name}/{dataset}/{ensemble}/'
    SMHI: '{dataset}/{ensemble}/{exp}/{frequency}'
    BSC: '{exp}/{dataset.lower}/{project.lower}-{expid}/*/*/{dataset}/{exp}/{ensemble}/{mip}/{short_name}'
  input_file: '{short_name}_{mip}_{dataset}_{exp}_{ensemble}*'
  output_file: '{project}_{dataset}_{mip}_{exp}_{ensemble}_{short_name}'
  institutes:
    'ACCESS1-0': ['CSIRO-BOM']
    'ACCESS1-3': ['CSIRO-BOM']
    'bcc-csm1-1': ['BCC']
    'bcc-csm1-1-m': ['BCC']
    'BNU-ESM': ['BNU']
    'CanAM4': ['CCCma']
    'CanCM4': ['CCCma']
    'CanESM2': ['CCCma']
    'CCSM4': ['NCAR']
    'CESM1-BGC': ['NSF-DOE-NCAR']
    'CESM1-CAM5': ['NSF-DOE-NCAR']
    'CESM1-CAM5-1-FV2': ['NSF-DOE-NCAR']
    'CESM1-FASTCHEM': ['NSF-DOE-NCAR']
    'CESM1-WACCM': ['NSF-DOE-NCAR']
    'CFSv2-2011': ['COLA-CFS', 'NOAA-NCEP']
    'CMCC-CESM': ['CMCC']
    'CMCC-CM': ['CMCC']
    'CMCC-CMS': ['CMCC']
    'CNRM-CM5': ['CNRM-CERFACS']
    'CNRM-CM5-2': ['CNRM-CERFACS']
    'CSIRO-Mk3-6-0': ['CSIRO-QCCCE']
    'EC-EARTH': ['ICHEC']
    'FGOALS-g2': ['LASG-CESS']
    'FGOALS-gl': ['LASG-IAP']
    'FGOALS-s2': ['LASG-IAP']
    'FIO-ESM': ['FIO']
    'fio-esm': ['FIO']
    'GEOS-5': ['NASA-GMAO']
    'GFDL-CM2p1': ['NOAA-GFDL']
    'GFDL-CM3': ['NOAA-GFDL']
    'GFDL-ESM2G': ['NOAA-GFDL']
    'GFDL-ESM2M': ['NOAA-GFDL']
    'GFDL-HIRAM-C180': ['NOAA-GFDL']
    'GFDL-HIRAM-C360': ['NOAA-GFDL']
    'GISS-E2-H': ['NASA-GISS']
    'GISS-E2-H-CC': ['NASA-GISS']
    'GISS-E2-R': ['NASA-GISS']
    'GISS-E2-R-CC': ['NASA-GISS']
    'HadCM3': ['MOHC']
    'HadGEM2-A': ['MOHC']
    'HadGEM2-AO': ['NIMR-KMA']
    'HadGEM2-CC': ['MOHC']
    'HadGEM2-ES': ['INPE', 'MOHC']
    'inmcm4': ['INM']
    'IPSL-CM5A-LR': ['IPSL']
    'IPSL-CM5A-MR': ['IPSL']
    'IPSL-CM5B-LR': ['IPSL']
    'MIROC-ESM': ['MIROC']
    'MIROC-ESM-CHEM': ['MIROC']
    'MIROC4h': ['MIROC']
    'MIROC5': ['MIROC']
    'MPI-ESM-LR': ['MPI-M']
    'MPI-ESM-MR': ['MPI-M']
    'MPI-ESM-P': ['MPI-M']
    'MRI-AGCM3-2H': ['MRI']
    'MRI-AGCM3-2S': ['MRI']
    'MRI-CGCM3': ['MRI']
    'MRI-ESM1': ['MRI']
    'NICAM-09': ['NICAM']
    'NorESM1-M': ['NCC']
    'NorESM1-ME': ['NCC']

OBS:
  input_dir:
    #default: '{tier}/{dataset}'
    default: '{tier}'
    BSC: '{type}/{institute.lower}/{dataset.lower}/{freq_folder}/{short_name}{freq_base}'
  input_file:
    default: '{project}_{dataset}_{type}_{version}_{field}_{short_name}_*'
    BSC: '{short_name}_*.nc'
  # output_file: '{project}_{dataset}_{type}_{short_name}'
  output_file: '{project}_{dataset}_{type}_{short_name}{freq_base}'
  cmor_type: 'CMIP6'
  cmor_strict: false

OBSanom:
  input_dir:
    #default: '{tier}/{dataset}'
    default: '{tier}'
    BSC: '{type}/{institute.lower}/{dataset.lower}/{freq_folder}/{short_name}anomaly{freq_base}'
  input_file:
    default: '{project}_{dataset}_{type}_{version}_{field}_{short_name}_*'
    BSC: '{short_name}anomaly_*.nc'
  # output_file: '{project}_{dataset}_{type}_{short_name}'
  output_file: '{project}_{dataset}_{type}_{short_name}{freq_base}'
  cmor_type: 'CMIP6'
  cmor_strict: false

OBSln:
  input_dir:
    #default: '{tier}/{dataset}'
    default: '{tier}'
    BSC: '{type}/{institute.lower}/{dataset.lower}/{freq_folder}/{short_name}{freq_base}'
  input_file:
    default: '{project}_{dataset}_{type}_{version}_{field}_{short_name}_*'
    BSC: '{short_name}_*.nc'
  # output_file: 'OBS_{dataset}_{type}_{short_name}'
  output_file: 'OBS_{dataset}_{type}_{short_name}{freq_base}'
  cmor_type: 'CMIP6'
  cmor_strict: false

BOUNDED_OBS:
  input_dir:
      BSC: 'BOUNDED_OBS_{version}/preproc/bounded_obs/'
  input_file:
      BSC: 'OBS_{dataset}_{type}_{short_name}{freq_base}_*_bounded.nc'
  output_file: '{project}_{dataset}_{type}_{short_name}'
  cmor_type: 'CMIP6'
  cmor_strict: false

CMOR_OBS:
  input_dir:
      default: '{tier}/{dataset.upper}'
      BSC: 'Tier{tier}/{dataset}'
  input_file:
      BSC: '{short_name}_*.nc'
      # BSC: 'OBS_{dataset}_{type}_{version}_{mip}_{short_name}_*.nc'
  output_file: '{project}_{dataset}_{type}_{short_name}'
  cmor_type: 'CMIP6'
  cmor_strict: false


obs4MIPs:
  cmor_strict: false
  input_dir:
    default: 'Tier{tier}/{dataset}'
  input_file: '{short_name}_{dataset}_{level}_{version}_*.nc'
  input_fx_dir:

obs4MIPs:
  cmor_strict: false
  input_dir:
    default: 'Tier{tier}/{dataset}'
  input_file: '{short_name}_{dataset}_{level}_{version}_*.nc'
  input_fx_dir:
    default: 'Tier{tier}/{dataset}'
  input_fx_file:
    default: '{project}_{dataset}_fx_{fx_var}.nc'
  output_file: '{project}_{dataset}_{level}_{version}_{short_name}'
  cmor_type: 'CMIP6'

ana4mips:
  cmor_strict: false
  input_dir:
    default: 'Tier{tier}/{dataset}'
  input_file: '{short_name}_{mip}_{type}_{dataset}_*.nc'
  output_file: '{project}_{mip}_{type}_{dataset}_{short_name}'
  cmor_type: 'CMIP5'

EMAC:
  input_dir:
    default: '{dataset}'
  input_file: ''
  output_file: '{dataset}_{ensemble}_{short_name}'
  cmor_type: 'CMIP5'

DCPP:
  input_dir:
    default: '/'
    BSC: '{expid}/{folder}/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
  input_file: '{short_name}_{mip}_{dataset}_{exp}_{startdate}-{ensemble}_{grid}*.nc'
  output_file: '{project}_{expid}_{dataset}_{mip}_{exp}_{startdate}-{ensemble}_{short_name}'
  cmor_type: 'CMIP6'


BSC:
 cmor_strict: false
 cmor_type: 'CMIP6'
 cmor_tables: '/esarchive/scratch/Earth/jvegas/bsc_cmor'
 input_dir:
   default: '/{type}/{institute.lower}/{dataset.lower}/{freq_name}/{short_name}{orig_freq}/'
 input_file: '{short_name}_*.nc'
 input_fx_dir:
   default: '/'
 input_fx_file: '{fx_var}_fx_{dataset}_{exp}_r0i0p0.nc'
 output_file: '{project}_{dataset}_{short_name}'
 institutes:
   'ERA5': ['ECMWF']
   'ERAINTERIM': ['ECMWF']
   'MERRA': ['NASA']
   'ESA': ['ESA']
   'system4_m1': ['ECMWF']
